---
pacman:
  - archlinux-keyring
  - linux-headers
  - xorg
  - zip
  - yad
  - youtube-dl
  - zathura
  - zathura-pdf-mupdf
  - qalculate-gtk
  - poppler
  - xpad
  - ntp
  - vim
  - upower
  - ttf-inconsolata
  - tree
  - kate
  - variety
  - bastet
  - texlive-most
  - termite
  - ranger
  - qt5
  - qt
  - python
  - gcolor2
  - virtualbox
  - virtualbox virtualbox-guest-iso
  - dash
  - pipewire-alsa
  - pipewire-jack
  - pipewire-pulse
  - hwinfo
  - pamixer
  - pulseaudio-alsa
  - alsa-utils
  - picom
  - ccache
  - xss-lock
  - xfce4-power-manager
  - dos2unix
  - dolphin
  - nitrogen
  - pandoc
  - networkmanager
  - ncdu
  - python-pip
  - git
  - flameshot
  - thunar-archive-plugin
  - dmenu
  - chromium
  - adwaita-icon-theme
  - bc
  - alacritty
  - figlet
  - feh
  - mpv
  - xmonad
  - xmonad-contrib
  - xmobar
  - neofetch
  - wmctrl
  - xdotool
  - pango
  - cups
  - system-config-printer
  - pavucontrol
  - qbittorrent
  - sddm
  - cpupower
  - cmus
  - yakuake
  - acpi
  - dunst
  - file-roller
  - libreoffice-still
  - awk
  - libmtp
  - usbutils
  - calcurse
  - libnotify
  - unzip
  - unrar
  - bluez
  - blueberry
  - xclip
  - tumbler
  - highlight
  - odt2txt
  - tmux
  - stalonetray
  - libva-utils
  - libva
  - libva-intel-driver
  - libva-vdpau-driver
  - lxappearance
  - python-pdftotext
  - ruby
  - xdotool
  - cmatrix
  - sysstat
  - ttf-nerd-fonts-symbols
  - ttf-font-awesome
  - tk
  - ttf-dejavu
  - kvantum-qt5
  - p7zip
  - testdisk
  - adobe-source-han-sans-cn-fonts
  - adobe-source-han-sans-hk-fonts
  - adobe-source-han-sans-jp-fonts
  - adobe-source-han-sans-kr-fonts
  - adobe-source-han-sans-otc-fonts
  - adobe-source-han-sans-tw-fonts
  - adobe-source-han-serif-cn-fonts
  - adobe-source-han-serif-jp-fonts
  - adobe-source-han-serif-kr-fonts
  - adobe-source-han-serif-otc-fonts
  - adobe-source-han-serif-tw-fonts
  - gsettings-qt
  - s-tui
  - terminus-font
  - code
  - jupyter
  - xfce4-notifyd
  - xorg-setxkbmap
  - numlockx
  - gtop
  - pstree
  - zsh
yay:
  - matcha-gtk-theme
  - luv-icon-theme-git
  - papirus-icon-theme
  - ttf-iosevka
  - nerd-fonts-fantasque-sans-mono
  - ttf-font-icons
  - otf-font-awesome
  - awesome-terminal-fonts
  - nerd-fonts-hack
  - gammy
  - light-git
  - topgrade
  - xkb-switch
  - kvantum-theme-matcha-git
  - ttf-iosevka-term
  - noto-fonts-emoji-apple
  - yakuake-skin-breeze-thin-dark
  - tela-icon-theme
  - cava
  - adobe-base-14-fonts
  - freezer-appimage
  - solarized-sddm-theme
  - code-marketplace
  - paru
  - bibata-cursor-theme-bin
  - ttf-envy-code-r
  - oh-my-zsh-git
  - virtualbox-ext-oracle
pip:
  - ueberzug
files:
  # .config dir
  - .config
  - '~'
  # emoji
  - local.conf
  - /etc/fonts/
  # yakuake theme
  - profile-1.profile
  - ~/.local/share/konsole/
  # xmonad
  - .xmonad
  - '~'
  # sddm
  - sddm.conf
  - /etc/
  # zsh
  - .zshrc
  - '~'
  # pacman.conf
  - pacman.conf
  - /etc/
  # sysinfo
  - sysinfo
  - ~/.bin/
  # fetch
  - fetch
  - ~/.bin/
  # rec.sh
  - rec.sh
  - ~/.bin/
  
